name: "Sonar_cloud_scan_github_action"
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - sonacloud
  # pull_request:
  #   branches:
  #     - main

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.organization=hashghost
            -Dsonar.projectKey=hashghost
            -Dsonar.python.coverage.reportPaths=coverage.xml
